### PR TITLE
Don't include default pattern when user specifies their own in Rake task.

### LINKED ISSUE #2303: Rake task regression? Runs 0 examples since RSpec 3.4.0
In a `Rakefile.rb` I have a rake task:
```ruby
::RSpec::Core::RakeTask.new(:spec) do |task|
 task.rspec_opts      = "--tty --color --format documentation --format h "\
  "--out ./rspec.html --pattern #{File.dirname(__FILE__)}/test/{unit,spec}/**/*_spec.rb"
end
```
When using RSpec 3.3.0, all is fine, all examples are run. But when I use RSpec 3.4.0, there are 0 examples run. I found out that there is the new way how to invoke rspec rake task:
```ruby
desc 'Run RSpec tests'
RSpec::Core::RakeTask.new(:spec) do |task, args|
  task.rspec_opts      = '--tty --color --format documentation --format h --out ./rspec.html'
  task.pattern         = "#{File.dirname(__FILE__)}/test/{unit,spec}/**/*_spec.rb"
end
```

Was such change intended or is it a regression?

### PR DESCRIPTION
**Pull request by JonRowe**
When configuring rspec via Rake task and a developer specifies a pattern via rspec_opts, don't include the default pattern. Should fix #2303.

### CODE REVIEW

File: spec/rspec/core/rake_task_spec.rb [hunk 1]
```diff
@@ -66,6 +66,11 @@ def spec_command
         task.rspec_opts = "-Ifoo"
         expect(spec_command).to match(/#{task.rspec_path}.*-Ifoo/)
       end
+
+      it 'wont add --pattern if rspec_opts includes --pattern' do
```
Comment (myronmarston) [inline spec/rspec/core/rake_task_spec.rb]: s/wont/does not/

(At least, we tend to use present-tense "does not" everywhere else in doc strings like these instead of future-tense "will not").

Comment (myronmarston) [inline spec/rspec/core/rake_task_spec.rb]: Also, this doc string is confusing.  It looks like it does show that it adds `--pattern` if `rspec_opts` includes `--pattern`.  How about:

``` ruby
it 'does not add the default --pattern if `rspec_opts` includes --pattern'
```

File: spec/rspec/core/rake_task_spec.rb [hunk 2]
```diff
@@ -66,6 +66,11 @@ def spec_command
...
+        task.rspec_opts = "--pattern some_specs"
+        expect(spec_command).to match(/#{task.rspec_path} --pattern some_specs$/)
+      end
```
Comment (myronmarston) [inline spec/rspec/core/rake_task_spec.rb]: On my initial read of this spec, I expected that it would pass even w/o your change -- after all, it's just showing that `--pattern some_specs` is included in the command, not that the default one is excluded.  After running it locally, I understand it now -- you are showing that the custom pattern comes after the rspec path and have an end-of-line anchor with `$` so it does show the default pattern not being included.  But it's a very implicit way to show it.  How about this instead:

``` ruby
expect(spec_command).to include("--pattern some_specs").and exclude(RSpec::Core::RakeTask::DEFAULT_PATTERN)
```

IMO, that's much more explicit and easy to understand.

**Comment by myronmarston** [comment]
Weird, this PR didn't build on travis.  Not sure why :(.

Anyhow, I definitely think that the change here is appropriate (if the user has configured `--pattern` in `rspec_opts` there's no reason to include the default pattern, too) but I think there's still a bug in the logic in #2002 that this does not address.  My understanding of #2002 is that it ORs together multiple patterns -- meaning that any spec files matching any of the patterns should get included in the loaded spec files.  But we are seeing in the case reported in #2303 that it does not work properly.  It seems like if someone runs `rspec --pattern pattern1 --pattern default_patern` (where `pattern1` is the pattern from example repo #2303) nothing would run and it would be a bug.

Do you have any plans to look more into that, @JonRowe?

**Comment by JonRowe** [comment]
> My understanding of #2002 is that it ORs together multiple patterns -- meaning that any spec files matching any of the patterns should get included in the loaded spec files. But we are seeing in the case reported in #2303 that it does not work properly. It seems like if someone runs rspec --pattern pattern1 --pattern default_pattern (where pattern1 is the pattern from example repo #2303) nothing would run and it would be a bug.

It actually did work for me on 3.5.0, and is working when `pattern` is used, because it's escaped, it's the fact the pattern is unescaped causes the misbehaviour, I'm not sure what to do about that...

**Comment by myronmarston** [comment]
> actually did work for me on 3.5.0, and is working when pattern is used, because it's escaped, it's the fact the pattern is unescaped causes the misbehaviour, I'm not sure what to do about that...

Strange, when I played around with the repo from #2303 I shellescaped the pattern (since I was getting a different error w/o it), and saw the exact issue reported by @xmik in #2303.  Did you try applying the patch I posted in that issue that allowed me to repro the issue?

**Comment by myronmarston** [comment]
Changes here LGTM, merge when green.

**Comment by JonRowe** [comment]
It's the one in `rspec_opts` that needs shell escaping, I was getting the reported behaviour identically on 3.3.x and 3.4.x whilst using it in my own project was working on 3.5.x

**Comment by myronmarston** [comment]
> It's the one in rspec_opts that needs shell escaping, I was getting the reported behaviour identically on 3.3.x and 3.4.x whilst using it in my own project was working on 3.5.x

I know, [my patch](https://github.com/rspec/rspec-core/issues/2303#issuecomment-235004624) escaped the alternate pattern everywhere it appeared, including in `rspec_opts`.  Did you try applying my patch?
