### PR TITLE
Setup profiler by default when ensuring listeners are ready

### LINKED ISSUE #2429: Using a deprecated API before setting `config.profile_examples` crashes  (and prevents profiling from working)
``` ruby
RSpec.configure do |c|
  c.treat_symbols_as_metadata_keys_with_true_values = true
  c.profile_examples = 1
end

RSpec.describe do
  example { }
end
```

When you run this, you get this error:

```

/Users/myron/moz/vanguard/bundle/ruby/2.1.0/gems/rspec-core-3.6.0/lib/rspec/core/reporter.rb:180:in `block in finish': undefined method `example_groups' for nil:NilClass (NoMethodError)
        from /Users/myron/moz/vanguard/bundle/ruby/2.1.0/gems/rspec-core-3.6.0/lib/rspec/core/reporter.rb:191:in `close_after'
        from /Users/myron/moz/vanguard/bundle/ruby/2.1.0/gems/rspec-core-3.6.0/lib/rspec/core/reporter.rb:171:in `finish'
        from /Users/myron/moz/vanguard/bundle/ruby/2.1.0/gems/rspec-core-3.6.0/lib/rspec/core/reporter.rb:81:in `report'
        from /Users/myron/moz/vanguard/bundle/ruby/2.1.0/gems/rspec-core-3.6.0/lib/rspec/core/runner.rb:112:in `run_specs'
        from /Users/myron/moz/vanguard/bundle/ruby/2.1.0/gems/rspec-core-3.6.0/lib/rspec/core/runner.rb:87:in `run'
        from /Users/myron/moz/vanguard/bundle/ruby/2.1.0/gems/rspec-core-3.6.0/lib/rspec/core/runner.rb:71:in `run'
        from /Users/myron/moz/vanguard/bundle/ruby/2.1.0/gems/rspec-core-3.6.0/lib/rspec/core/runner.rb:45:in `invoke'
        from /Users/myron/moz/vanguard/bundle/ruby/2.1.0/gems/rspec-core-3.6.0/exe/rspec:4:in `<top (required)>'
        from ./bin/rspec:14:in `load'
        from ./bin/rspec:14:in `<main>'
```

The problem is that in the reporter, `@profiler` is initially `nil`, then gets set [in setup_profiler](https://github.com/rspec/rspec-core/blob/edc7ce29f10d9d7af54ca743d76125ce130e11c4/lib/rspec/core/reporter.rb#L31) only if [profiling is enabled](https://github.com/rspec/rspec-core/blob/edc7ce29f10d9d7af54ca743d76125ce130e11c4/lib/rspec/core/formatters.rb#L135-L137) when defaults are being setup.  At [the end of the run](https://github.com/rspec/rspec-core/blob/edc7ce29f10d9d7af54ca743d76125ce130e11c4/lib/rspec/core/reporter.rb#L180), `@profiler` is assumed to be non-nil if profiling is enabled.  All that works together so that if `config.profile_examples` is set _after_ the first notification is sent, such as the use of a deprecated config API, then profiling will not be happening, and RSpec will crash at the end of the run.

@JonRowe I believe you set this stuff up.  Do you have an idea how to fix it?

### PR DESCRIPTION
**Pull request by JonRowe**
This should fix #2429 @myronmarston

### CODE REVIEW

File: spec/rspec/core/reporter_spec.rb [hunk 1]
```diff
@@ -36,6 +36,10 @@ module RSpec::Core
         reporter.finish
       end
 
+      it "will allow profiling when activated after formatter is used" do
+        config.profile_examples = 10
+        reporter.finish
+      end
```
Comment (myronmarston) [inline spec/rspec/core/reporter_spec.rb]: It's not clear to me how the this example shows a formatter being used before profiling is activated--profiling activation looks like the first thing that happens in this spec.

File: lib/rspec/core/reporter.rb [hunk 2]
```diff
@@ -231,6 +231,7 @@ def ensure_listeners_ready
       return if @setup
 
       @setup_default.call
+      setup_profiler
```
Comment (myronmarston) [inline lib/rspec/core/reporter.rb]: Should we remove the other `setup_profiler` call site and just let this be the one call site for it, since, AFAIK, the other one is no longer necessary with this?  Also, can we make `setup_profiler` private?

File: lib/rspec/core/profiler.rb [hunk 3]
```diff
@@ -20,7 +20,9 @@ def example_group_started(notification)
       def example_group_finished(notification)
         return unless notification.group.top_level?
 
-        @example_groups[notification.group][:total_time] =  Time.now - @example_groups[notification.group][:start]
+        if @example_groups[notification.group][:start]
+          @example_groups[notification.group][:total_time] =  Time.now - @example_groups[notification.group][:start]
```
Comment (myronmarston) [inline lib/rspec/core/profiler.rb]: `@example_groups[notification.group][:start]` is evaluated twice here and `@example_groups[notification.group]` is evaluated three times, which seems wasteful.  Can we refactor to not re-evaluate things?  Maybe this:

``` ruby
group = @example_groups[notification.group]
group[:total_time] = Time.now - group[:start] if group.key?(:start)
```

File: lib/rspec/core/reporter.rb (hunk 2 above)
Comment (JonRowe) [reply lib/rspec/core/reporter.rb]: Inlined it into the setup call.

File: spec/rspec/core/reporter_spec.rb (hunk 1 above)
Comment (JonRowe) [reply spec/rspec/core/reporter_spec.rb]: Changed to stub the config check to make it clearer, as profiler activation was manual before this actually did break without the code change tho.

File: lib/rspec/core/profiler.rb (hunk 3 above)
Comment (JonRowe) [reply lib/rspec/core/profiler.rb]: Sure

File: spec/rspec/core/reporter_spec.rb [hunk 4]
```diff
@@ -36,6 +35,10 @@ module RSpec::Core
         reporter.finish
       end
 
+      it "will allow profiling when activated after formatter is used" do
+        allow(config).to receive(:profile_examples?) { true }
+        reporter.finish
+      end
```
Comment (myronmarston) [inline spec/rspec/core/reporter_spec.rb]: I still find this spec confusing.

* Why does `allow(config).to receive(:profile_examples?) { true }` count as activating the formatter?
* The doc string says "after formatter is used" but I don't see where the formatter is used...unless `reporter.finish` counts as the formatter being used, but in that case the spec is showing the profiling activated before the formatter is used, in contradiction to the doc string.
* It's not clear what this example is asserting, as there's no expectation.  I know that the original failure was an exception which must not be raised anymore, but without the context of knowing about the original failure I think this spec will be confusing when we come to it in the future.

I suspect that all these issues stem from the fact that this is a highly isolated unit test.  A higher level spec in `spec/integration` might solve these issues.  Or maybe you can find a better way to do this as a unit test :).

Comment (JonRowe) [reply spec/rspec/core/reporter_spec.rb]: > * Why does `allow(config).to receive(:profile_examples?) { true }` count as activating the formatter?

We're not activating the formatter, in fact the opposite, we're trying to show that the profiler causes no issues when not initialised manually.

> * The doc string says "after formatter is used" but I don't see where the formatter is used...unless `reporter.finish` counts as the formatter being used, but in that case the spec is showing the profiling activated before the formatter is used, in contradiction to the doc string.

> * It's not clear what this example is asserting, as there's no expectation.  I know that the original failure was an exception which must not be raised anymore, but without the context of knowing about the original failure I think this spec will be confusing when we come to it in the future.

These two points I've tried to address with re-wording, the point is to prove the profiler is now automatically setup.

> A higher level spec in `spec/integration` might solve these issues.  Or maybe you can find a better way to do this as a unit test :).

I tried to use your example to do just that, however it proved non trivial, as we cannot truely replicate this scenario in isolation.

File: spec/rspec/core/reporter_spec.rb [hunk 5]
```diff
@@ -36,6 +35,12 @@ module RSpec::Core
         reporter.finish
       end
 
+      it "will allow profiler to be used without being properly setup" do
```
Comment (myronmarston) [inline spec/rspec/core/reporter_spec.rb]: Thanks, this wording is a lot more clear.

s/will allow/allows/ (shorter and more inline with the phrasing we use elsewhere).

File: spec/rspec/core/reporter_spec.rb [hunk 6]
```diff
@@ -36,6 +35,12 @@ module RSpec::Core
...
+        allow(config).to receive(:profile_examples?) { true }
```
Comment (myronmarston) [inline spec/rspec/core/reporter_spec.rb]: Does this have to stub `config`?  Or can it repro the issue using `config.profile_examples = true`?  In general, I prefer avoiding stubbing in these situations unless it's necessary.

Comment (JonRowe) [reply spec/rspec/core/reporter_spec.rb]: No it doesn't I changed it because of your earlier concern that this was activating the formatter.

File: spec/rspec/core/reporter_spec.rb (hunk 5 above)
Comment (JonRowe) [reply spec/rspec/core/reporter_spec.rb]: I've reworded.
