### PR TITLE
Fix next failure

### LINKED ISSUE #1910: `--next-failure` should not force `--order defined` in the user passes a seed
`--next-failure` (new in #1888) forces `--order defined` in order to make it deterministic which example you'll get -- otherwise it could bounce around to different examples, rendering the option hard to use.  However, if the user runs `rspec --next-failure --seed 1234` we should honor that seed rather than forcing `--order defined`.

### PR DESCRIPTION
**Pull request by myronmarston**
This fixes #1910 and #1914.

### CODE REVIEW

**Comment by JonRowe** [comment]
LGTM

File: lib/rspec/core/example_group.rb [hunk 1]
```diff
@@ -511,10 +506,7 @@ def self.run_after_context_hooks(example_group_instance)
 
       # Runs all the examples in this group.
       def self.run(reporter=RSpec::Core::NullReporter)
-        if RSpec.world.wants_to_quit
-          RSpec.world.clear_remaining_example_groups if top_level?
-          return
```
Comment (JonRowe) [inline lib/rspec/core/example_group.rb]: Historically this is for fast-fail right? Which still works so seems like a hangover from previous times...

Comment (myronmarston) [inline lib/rspec/core/example_group.rb]: Yep.  Read my commit message for the history (I dug into it):

e747c7fc4a506d1cbe643ddf57ad626773b8396f
