### PR TITLE
Prevent invalid cause from breaking exception presenter

### LINKED ISSUE #2701: The error during tests execution
### Subject of the issue
When I executed tests where raised custom Exception RSpec is failed with status 0.
Thus CI think that tests are ok and we have a false positive issue.

I faced with it in a real project which uses `connect-sdk-ruby` gem, [this exception](https://github.com/Ingenico-ePayments/connect-sdk-ruby/blob/c72f4c8289b883063e8773390dbd80173fb74c15/lib/ingenico/connect/sdk/communication_exception.rb) was raised.

### Your environment
* Ruby version: 2.6.5
* rspec-core version: latest master (revision da87aa0c5f25a6e6f2db6f0c8fb2a04625b80ac6)

### Steps to reproduce

1. Clone my repository https://github.com/Riddlerrr/rspec-exception-issue
2. Run `bundle exec rspec exception_spec.rb`

### Expected behavior
RSpec should print failures. For example:
```
Failures:

  1) Test exeption successfully output exeption
     Failure/Error: raise RuntimeError.new("RSpec error")
     
     RuntimeError:
       RSpec error
     # ./exception_spec.rb:20:in `block (2 levels) in <top (required)>'
```

### Actual behavior
```
bundler: failed to load command: rspec (/Users/sergey/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/bin/rspec)
NoMethodError: undefined method `cause' for "RSpec error":String
Did you mean?  case
  /Users/sergey/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/bundler/gems/rspec-core-da87aa0c5f25/lib/rspec/core/formatters/exception_presenter.rb:98:in `final_exception'
  /Users/sergey/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/bundler/gems/rspec-core-da87aa0c5f25/lib/rspec/core/formatters/exception_presenter.rb:101:in `final_exception'
  /Users/sergey/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/bundler/gems/rspec-core-da87aa0c5f25/lib/rspec/core/formatters/exception_presenter.rb:46:in `formatted_cause'
  /Users/sergey/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/bundler/gems/rspec-core-da87aa0c5f25/lib/rspec/core/formatters/exception_presenter.rb:41:in `formatted_backtrace'
  /Users/sergey/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/bundler/gems/rspec-core-da87aa0c5f25/lib/rspec/core/formatters/exception_presenter.rb:72:in `colorized_formatted_backtrace'
  /Users/sergey/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/bundler/gems/rspec-core-da87aa0c5f25/lib/rspec/core/formatters/exception_presenter.rb:240:in `formatted_message_and_backtrace'
  /Users/sergey/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/bundler/gems/rspec-core-da87aa0c5f25/lib/rspec/core/formatters/exception_presenter.rb:86:in `fully_formatted_lines'
  /Users/sergey/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/bundler/gems/rspec-core-da87aa0c5f25/lib/rspec/core/formatters/exception_presenter.rb:78:in `fully_formatted'
  /Users/sergey/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/bundler/gems/rspec-core-da87aa0c5f25/lib/rspec/core/notifications.rb:200:in `fully_formatted'
  /Users/sergey/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/bundler/gems/rspec-core-da87aa0c5f25/lib/rspec/core/notifications.rb:114:in `block in fully_formatted_failed_examples'
  /Users/sergey/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/bundler/gems/rspec-core-da87aa0c5f25/lib/rspec/core/notifications.rb:113:in `each'
  /Users/sergey/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/bundler/gems/rspec-core-da87aa0c5f25/lib/rspec/core/notifications.rb:113:in `each_with_index'
  /Users/sergey/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/bundler/gems/rspec-core-da87aa0c5f25/lib/rspec/core/notifications.rb:113:in `fully_formatted_failed_examples'
  /Users/sergey/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/bundler/gems/rspec-core-da87aa0c5f25/lib/rspec/core/formatters/base_text_formatter.rb:32:in `dump_failures'
  /Users/sergey/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/bundler/gems/rspec-core-da87aa0c5f25/lib/rspec/core/reporter.rb:209:in `block in notify'
  /Users/sergey/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/bundler/gems/rspec-core-da87aa0c5f25/lib/rspec/core/reporter.rb:208:in `each'
  /Users/sergey/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/bundler/gems/rspec-core-da87aa0c5f25/lib/rspec/core/reporter.rb:208:in `notify'
  /Users/sergey/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/bundler/gems/rspec-core-da87aa0c5f25/lib/rspec/core/reporter.rb:178:in `block in finish'
  /Users/sergey/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/bundler/gems/rspec-core-da87aa0c5f25/lib/rspec/core/reporter.rb:194:in `close_after'
  /Users/sergey/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/bundler/gems/rspec-core-da87aa0c5f25/lib/rspec/core/reporter.rb:174:in `finish'
  /Users/sergey/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/bundler/gems/rspec-core-da87aa0c5f25/lib/rspec/core/reporter.rb:76:in `report'
  /Users/sergey/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/bundler/gems/rspec-core-da87aa0c5f25/lib/rspec/core/runner.rb:115:in `run_specs'
  /Users/sergey/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/bundler/gems/rspec-core-da87aa0c5f25/lib/rspec/core/runner.rb:89:in `run'
  /Users/sergey/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/bundler/gems/rspec-core-da87aa0c5f25/lib/rspec/core/runner.rb:71:in `run'
  /Users/sergey/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/bundler/gems/rspec-core-da87aa0c5f25/lib/rspec/core/runner.rb:45:in `invoke'
  /Users/sergey/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/bundler/gems/rspec-core-da87aa0c5f25/exe/rspec:4:in `<top (required)>'
  /Users/sergey/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/bin/rspec:23:in `load'
  /Users/sergey/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/bin/rspec:23:in `<top (required)>'
```

### PR DESCRIPTION
**Pull request by JonRowe**
Fixes #2701

### CODE REVIEW

**Comment by JonRowe** [comment]
Don't merge this yet as I think something is wrong

File: spec/rspec/core/formatters/exception_presenter_spec.rb [hunk 1]
```diff
@@ -12,6 +12,10 @@ module RSpec::Core
       allow(example.execution_result).to receive(:exception) { exception }
       example.metadata[:absolute_file_path] = __FILE__
       allow(exception).to receive(:cause) if RSpec::Support::RubyFeatures.supports_exception_cause?
+      allow(Exception).to receive(:===).and_wrap_original do |original, *other|
+        return false if String === true
```
Comment (pirj) [inline spec/rspec/core/formatters/exception_presenter_spec.rb]: I'm having a hard time understanding how `String === true` works and when it can evaluate to `true`.

Comment (JonRowe) [reply spec/rspec/core/formatters/exception_presenter_spec.rb]: This doesn't work, it messes with the exceptions to much, but the premiss was this, we're detecting if `cause` is returning exceptions, `Exception === other` will return true for any instance that extends it, the deliberately broken example used a string so I was saying, hey all things are exceptions except for strings.

**Comment by JonRowe** [comment]
@pirj this is ready for review.

File: spec/rspec/core/formatters/exception_presenter_spec.rb [hunk 2]
```diff
@@ -211,8 +224,9 @@ module RSpec::Core
 
       it 'wont produce a stack error when the cause is an older exception', :if => RSpec::Support::RubyFeatures.supports_exception_cause? do
         allow(the_exception).to receive(:cause) do
```
Comment (pirj) [inline spec/rspec/core/formatters/exception_presenter_spec.rb]: Is this needed? `the_exception` and `second_exception` point fingers at each other already.

File: spec/rspec/core/formatters/exception_presenter_spec.rb [hunk 3]
```diff
@@ -230,6 +244,31 @@ module RSpec::Core
         EOS
       end
 
+      it 'will work when cause is incorrectly overridden', :if => RSpec::Support::RubyFeatures.supports_exception_cause? do
+        exception_klass = Class.new(Exception) do
+          def cause
+            "An incorrect implementation"
+          end
+        end
+        incorrect_cause_exception = exception_klass.new
```
Comment (pirj) [inline spec/rspec/core/formatters/exception_presenter_spec.rb]: Can this be just `FakeException.new("Boom", [], "An incorrect implementation")`?

File: spec/rspec/core/formatters/exception_presenter_spec.rb (hunk 2 above)
Comment (JonRowe) [reply spec/rspec/core/formatters/exception_presenter_spec.rb]: Yes, this is a loop. The others don't loop. (the_exception => second_exception => first_exception => nil)

File: spec/rspec/core/formatters/exception_presenter_spec.rb (hunk 3 above)
Comment (JonRowe) [reply spec/rspec/core/formatters/exception_presenter_spec.rb]: Good point, this predated the refactoring exceptions to make it work :joy:

File: spec/rspec/core/formatters/exception_presenter_spec.rb (hunk 2 above)
Comment (pirj) [reply spec/rspec/core/formatters/exception_presenter_spec.rb]: Oh, I've mixed `first_exception` with `the_exception` in `second_exception`'s cause.
👍

File: spec/rspec/core/formatters/exception_presenter_spec.rb (hunk 3 above)
Comment (JonRowe) [reply spec/rspec/core/formatters/exception_presenter_spec.rb]: Fixed.

**Comment by pirj** [comment]
Green!

**Comment by JonRowe** [comment]
Good catch @pirj, I'd forgotten to check on this :joy: I redid your fix slightly and rebased.
