### PR TITLE
Issue warning for shared example group without definition

### LINKED ISSUE #2212: shared_examples should raise error if no block passed [new feature]
I found in a code base I'm working with that someone by mistake uses  `shared_examples` instead `it_behaves_like`. 
And it strange that:
- shared examples not run
- nothing like an error message or a warning

I think there no one need use `shared_examples` without a block. I think that better to add exception or warning message.

### PR DESCRIPTION
**Pull request by JonRowe**
Issue a warning for a missing block when defining a shared example group.

closes #2212

### CODE REVIEW

File: spec/rspec/core/shared_example_group_spec.rb [hunk 1]
```diff
@@ -57,6 +57,11 @@ module Core
             expect(Kernel).to_not respond_to(shared_method_name)
           end
 
+          it "displays a waraning when adding an example group without a block" do
```
Comment (myronmarston) [inline spec/rspec/core/shared_example_group_spec.rb]: s/waraning/warning/

Comment (JonRowe) [inline spec/rspec/core/shared_example_group_spec.rb]: Fixed :)

**Comment by myronmarston** [comment]
LGTM, merge when green.

**Comment by JonRowe** [comment]
I've tried to solve this several times, but I'm not sure why this fails on 1.8.7 and can't install 1.8.7, any ideas?

**Comment by JonRowe** [comment]
Taking the prior LGTM as an it's ok to merge, I only fixed the specs.
