### PR TITLE
Use :rerun_file_path when checking location filters

### LINKED ISSUE #1961: 3.2.2 breaks line number filter when external shared examples are included
In going from `rspec-core` 3.2.1 to `rspec-core` 3.2.2 (included into the bundle via `rspec-rails`), I've noticed that CLI commands in the form:

```
> bundle exec foo.rb:123
```

where `123` is the start/inner line of an `it` block no longer behave as expected. In 3.2.1, only that single test would be run. In 3.2.2 all `it_behaves_like` blocks in the file get executed before running the indicated test. This can add significantly to the amount of time needed to interactively run tests if there are many tests defined inside the `shared_examples` block that `it_behaves_like` refers to.

The bug/change is still present in 3.2.3 but I have not tested against `master`.

## Issue

Appears to occur when shared examples are `require`d from an external file.

## Reproducing

Setup files as below (or `git clone https://github.com/bentheax/sample-rspec-for-bug-report.git`) and run

```
> bundle exec rspec spec/minimal_spec.rb:7
```
**`Gemfile`**

```ruby
source "https://rubygems.org"

gem "rspec"
gem "rspec-core", "=3.2.2"
```

**`Gemfile.lock`**

```
GEM
  remote: https://rubygems.org/
  specs:
    diff-lcs (1.2.5)
    rspec (3.2.0)
      rspec-core (~> 3.2.0)
      rspec-expectations (~> 3.2.0)
      rspec-mocks (~> 3.2.0)
    rspec-core (3.2.2)
      rspec-support (~> 3.2.0)
    rspec-expectations (3.2.1)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.2.0)
    rspec-mocks (3.2.1)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.2.0)
    rspec-support (3.2.2)

PLATFORMS
  ruby

DEPENDENCIES
  rspec
  rspec-core (= 3.2.2)
```

**`spec/a_test_that_always_runs_external_examples.rb`**

```ruby
shared_examples "a test that always runs external examples" do
  it "runs me, for instance" do
    raise "this line should never be executed"
  end
end
```

**`spec/minimal_spec.rb`**

```ruby
require_relative "./a_test_that_always_runs_external_examples"

describe "rspec_with_line_number" do
  it_behaves_like "a test that always runs external examples"

  it "has a test that I'd like to run on its own" do
    expect(1).to eq(1)
  end
end
```

## Output

```
> bundle exec rspec -fd spec/minimal_spec.rb:7
Run options: include {:locations=>{"./spec/minimal_spec.rb"=>[7]}}

rspec_with_line_number
  has a test that I'd like to run on its own
  behaves like a test that always runs external examples
    runs me, for instance (FAILED - 1)

Failures:

  1) rspec_with_line_number behaves like a test that always runs external examples runs me, for instance
     Failure/Error: raise "this line should never be executed"
     RuntimeError:
       this line should never be executed
     Shared Example Group: "a test that always runs external examples" called from ./spec/minimal_spec.rb:4
     # ./spec/a_test_that_always_runs_external_examples.rb:3:in `block (2 levels) in <top (required)>'

Finished in 0.00151 seconds (files took 0.0792 seconds to load)
2 examples, 1 failure

Failed examples:

rspec ./spec/minimal_spec.rb:4 # rspec_with_line_number behaves like a test that always runs external examples runs me, for instance
```

### PR DESCRIPTION
**Pull request by bentheax**
Fixes #1961

The problem with using `:absolute_file_path` is that it doesn't function
correctly for shared examples in an external file. The filter manager thinks
that there are no location filters set, when actually there are.

Since `MetadataFilter` already handles location filtering correctly across multiple
nested examples / files, correcting the path that is checked is sufficient to
fix the line filtering issue.

### CODE REVIEW

File: lib/rspec/core/filter_manager.rb [hunk 1]
```diff
@@ -99,13 +99,17 @@ def prune_conditionally_filtered_examples(examples)
...
-        return yield if no_location_filters && no_id_filters
-
-        MetadataFilter.filter_applies?(:ids, ids, ex_metadata) ||
-        MetadataFilter.filter_applies?(:locations, locations, ex_metadata)
+        has_id_filters = ids[ex_metadata[:rerun_file_path]].any?
+        has_location_filters = locations[
+          File.expand_path(ex_metadata[:rerun_file_path])
+        ].any?
+
+        if has_location_filters || has_id_filters
```
Comment (JonRowe) [inline lib/rspec/core/filter_manager.rb]: I think I'd prefer that this was expressed as a guard condition like before, e.g.
`return yield unless has_location_filters || has_id_filters`

**Comment by JonRowe** [comment]
A style quibble but otherwise this looks good to me! Good job :)

**Comment by myronmarston** [comment]
I have a concern before its merged but am on my phone right now so it takes too much effort to explain at the  moment.  I'll try to review this before bed tonight.

**Comment by bentheax** [comment]
> A style quibble but otherwise this looks good to me! Good job :)

Thanks. I have returned it as closely as possible to the original style. Will squash back down again once I've heard the concern around the fix and made whatever changes are needed there.

File: lib/rspec/core/filter_manager.rb [hunk 2]
```diff
@@ -99,8 +99,10 @@ def prune_conditionally_filtered_examples(examples)
       # defined in the same file as the location filters. Excluded specs in
       # other files should still be excluded.
       def file_scoped_include?(ex_metadata, ids, locations)
-        no_location_filters = locations[ex_metadata[:absolute_file_path]].empty?
         no_id_filters = ids[ex_metadata[:rerun_file_path]].empty?
+        no_location_filters = locations[
+          File.expand_path(ex_metadata[:rerun_file_path])
+        ].empty?
```
Comment (myronmarston) [inline lib/rspec/core/filter_manager.rb]: I have a concern here: location filtering is based on `absolute_file_path`, not `rerun_file_path` (see [this code](https://github.com/rspec/rspec-core/blob/98ade33737c1c2848aa6e32da286feef49065e8d/lib/rspec/core/metadata_filter.rb#L70)) since location filtering is based on where the example is _defined_, and it therefore seems potentially problematic to only check `rerun_file_path` here.  If we wanted to be paranoid this line could be:

``` ruby
no_location_filters = locations[
  File.expand_path(ex_metadata[:rerun_file_path])
].empty? && locations[ex_metadata[:absolute_file_path]].empty?
```

That said, I've been trying to think of an edge case that would require this extra bit of logic and I haven't been able to come up with one.  I'm not a fan of adding logic "just in case" so if we can't come up with an example that requires it to work properly I'd say we should just go with what you have here....but I figured it was worth bringing up to see if anyone can think of an example that would require that.

@JonRowe and @bentheax -- can either of you think of a case like that?

**Comment by myronmarston** [comment]
> Thanks. I have returned it as closely as possible to the original style. Will squash back down again once I've heard the concern around the fix and made whatever changes are needed there.

:+1:  Thanks for doing that.  It's much easier to see what you've changed now :).

File: lib/rspec/core/filter_manager.rb (hunk 2 above)
Comment (bentheax) [inline lib/rspec/core/filter_manager.rb]: @myronmarston Ah yes that's a good point, but I can't think of a practical use case that relies on that behaviour.

The closest I can imagine is running same inner example from a shared example group across multiple rerun files. You'd have to use a dummy locations i.e. -

`rspec shared.rb:5 includes_shared_1.rb:999 includes_shared_2.rb:999`

Of course, if you want to do that you'd just use a tag on the example you want to test.

Comment (myronmarston) [inline lib/rspec/core/filter_manager.rb]: Let's go with what you have then.

**Comment by JonRowe** [comment]
Thanks!
