### PR TITLE
Fix block support in example.duplicate_with

### LINKED ISSUE #2297: LocalJumpError: no block given when using duplicate_with API
I have created [a reduced test case](https://github.com/bootstraponline/rspec_dupe_fail) that replicates the problem. I'm using the duplicate API like this:

```ruby
example_group.descendants.each do |desc_group|
  desc_group.examples.clone.each do |ex|
    config.caps.each do |cap|
      ex.duplicate_with(caps: cap)
    end

    # remove example without caps
    desc_group.remove_example ex
  end
end
```

which errors:

```ruby
# Failure/Error: @example_group_instance.instance_exec(self, &@example_block)
#
# LocalJumpError:
#     no block given
# gems/rspec-core-3.5.1/lib/rspec/core/example.rb:252:in `instance_exec'
#
# @example_block in example.rb is nil.
#
```
> https://travis-ci.org/bootstraponline/rspec_dupe_fail/builds/145897221

If I go back to using monkey patching then everything works correctly.

```ruby
# working version.
example_group.descendants.each do |desc_group|
  new_examples = []
  desc_group.examples.each do |ex|
    config.caps.each_with_index do |cap, index|
      ex_with_cap = ex.clone
      new_id      = "#{ex_with_cap.id}_#{index}_#{cap}"
      ex_with_cap.instance_variable_set(:@id, new_id)
      ex_with_cap.caps = cap
      new_examples << ex_with_cap
    end
  end
  desc_group.instance_variable_set(:@examples, new_examples)
end
```

Why does `duplicate_with` create an example with a nil `@example_block`?

### PR DESCRIPTION
**Pull request by bootstraponline**
Fix #2297

### CODE REVIEW

File: spec/rspec/core/example_spec.rb [hunk 1]
```diff
@@ -90,7 +90,10 @@ def metadata_hash(*args)
       # ensure metadata is unique for each example
       expect(example.metadata.object_id).to_not eq(example2.metadata.object_id)
       expect(example.metadata[:custom_key]).to eq(nil)
+      expect(example.metadata[:block]).to_not eq(nil)
+
       expect(example2.metadata[:custom_key]).to eq(:custom_value)
+      expect(example2.metadata[:block]).to_not eq(nil)
```
Comment (myronmarston) [inline spec/rspec/core/example_spec.rb]: Instead of just asserting it is not nil, it would be good to make a positive assertion.  How about `expect(&example.metadata[:block]).to raise_error("first")`?

Comment (bootstraponline) [inline spec/rspec/core/example_spec.rb]: Great idea. Updated.

**Comment by bootstraponline** [comment]
> features/command_line/bisect.feature:93 

^ failed on jruby, seems unrelated.

**Comment by bootstraponline** [comment]
All tests passing. jruby is flaky.

File: lib/rspec/core/example.rb [hunk 2]
```diff
@@ -138,8 +138,10 @@ def duplicate_with(metadata_overrides={})
 
         # don't clone the example group because the new example
         # must belong to the same example group (not a clone).
+        #
+        # block is nil in new_metadata so we have to get it from metadata.
         Example.new(example_group, description.clone,
-                    new_metadata, new_metadata[:block])
+                    new_metadata, metadata[:block])
```
Comment (JonRowe) [inline lib/rspec/core/example.rb]: I think it makes sense to do `metadata[:block].clone`, as thats what `new_metadata` is, but somehow it's missing the block from its clone.

Comment (myronmarston) [inline lib/rspec/core/example.rb]: It's missing because  of the code on lines 135-137 that deletes the reserved keys.

Comment (JonRowe) [inline lib/rspec/core/example.rb]: Make sense, I think it still makes sense to clone it?

Comment (myronmarston) [inline lib/rspec/core/example.rb]: AFAIK, blocks are immutable, so I'm not sure what cloning it does for us other than taking more memory and time.

Comment (JonRowe) [inline lib/rspec/core/example.rb]: Ok, LGTM then

**Comment by JonRowe** [comment]
Thanks @bootstraponline

**Comment by bootstraponline** [comment]
Thanks!
