### PR TITLE
Make World.reset also reset example group counts

### LINKED ISSUE #2721: How to run second test example with RSpec::Core::Runner for the same test file
### Subject of the issue
I use `RSpec::Core::Runner` to run specs https://relishapp.com/rspec/rspec-core/v/3-3/docs/running-specs-multiple-times-with-different-runner-options-in-the-same-process

I run test files and test examples (i.e. spec/example_spec.rb[1:1]) at the same time. I'm getting test files and test example paths from external API. Sometimes it can happen that `RSpec::Core::Runner` will have to run a second test example `B1` from the test file `spec/example_spec.rb` for which we already run first test example `A1` but the second test example `B1` is ignored. I don't know how to force RSpec to run `B1` test :(

I tried to dig into the source code of RSpec for the last 3 days but I'm stuck. Any help or tips where can I look for a solution would be great.

### Your environment
* Ruby version: 2.6.5
* rspec-core version: 3.9.1

### Steps to reproduce

Source code: https://github.com/ArturT/rspec-test-examples

```ruby
# spec/example_spec.rb
describe 'Example 1' do
  it 'A1' do
    expect(true).to be true
  end

  it 'B1' do
    expect(true).to be true
  end
end
```

```ruby
# spec/example2_spec.rb
describe 'Example 2' do
  it 'A2' do
    expect(true).to be true
  end

  it 'B2' do
    expect(true).to be true
  end
end
```

```ruby
# spec/example3_spec.rb
describe 'Example 3' do
  it 'A3' do
    expect(true).to be true
  end

  it 'B3' do
    expect(true).to be true
  end
end
```

Script to run tests:

```ruby
# run_tests.rb
puts 'Run tests'

require 'rspec/core'

def start_runner(cli_args)
  puts '-'*50
  args = ['--format', 'documentation'] + cli_args
  options = RSpec::Core::ConfigurationOptions.new(args)
  RSpec::Core::Runner.new(options).run($stderr, $stdout)

  RSpec.clear_examples
end


cli_args = ['spec/example_spec.rb[1:1]', 'spec/example2_spec.rb']
start_runner(cli_args)

cli_args = ['spec/example_spec.rb[1:2]', 'spec/example3_spec.rb']
start_runner(cli_args)
```

### Expected behavior

```
$ ruby run_tests.rb
Run tests
--------------------------------------------------
Run options: include {:ids=>{"./spec/example_spec.rb"=>["1:1"]}}

Example 1
  A1

Example 2
  A2
  B2

Finished in 0.00182 seconds (files took 0.16182 seconds to load)
3 examples, 0 failures

--------------------------------------------------
Run options: include {:ids=>{"./spec/example_spec.rb"=>["1:2"]}}

Example 1
  B1              <---- example B1 should run here

Example 3
  A3
  B3

Finished in 0.00056 seconds (files took 0.00535 seconds to load)
2 examples, 0 failures
```

### Actual behavior

```
$ ruby run_tests.rb
Run tests
--------------------------------------------------
Run options: include {:ids=>{"./spec/example_spec.rb"=>["1:1"]}}

Example 1
  A1

Example 2
  A2
  B2

Finished in 0.00182 seconds (files took 0.16182 seconds to load)
3 examples, 0 failures

--------------------------------------------------
Run options: include {:ids=>{"./spec/example_spec.rb"=>["1:2"]}}

Example 3
  A3
  B3

Finished in 0.00056 seconds (files took 0.00535 seconds to load)
2 examples, 0 failures
```

### PR DESCRIPTION
**Pull request by agis**
If we don't reset example group counts in custom runners that run from
the same process, example metadata end up being published with incorrect
scoped IDs.

`World#example_group_counts_by_spec_file` is merely added for testability.

Fixes #2721

### CODE REVIEW

**Comment by JonRowe** [comment]
Can we get a spec for this? Something along the lines of creating a world, adding some examples and showing that the hash is not 0 unless reset?

**Comment by agis** [comment]
@JonRowe I was instead thinking something on a higher-level, like:

```ruby
require "rspec/core"
require "stringio"

# RSpec.describe "foo" do
#   it "bar" do
#     expect(true).to be true
#   end
# end

def truncate_timings(output)
	output.gsub(/Finished in.*\n/, '')
end

expected_output = StringIO.new
actual_output = StringIO.new

opts = RSpec::Core::ConfigurationOptions.new(["./foo_spec.rb[1:1]"])
RSpec::Core::Runner.new(opts).run(nil, $stderr)
expected_output = truncate_timings(expected_output.string)

RSpec.clear_examples

opts = RSpec::Core::ConfigurationOptions.new(["./foo_spec.rb[1:1]"])
RSpec::Core::Runner.new(opts).run(nil, $stderr)
actual_output = truncate_timings(actual_output.string)

# expected_output == actual_output
```

Thoughts? I think this way it's more apparent what the fix is about.

If that seems good, could you point me to some similar specs from RSpec's codebase which I can follow as examples?

That said, I don't really like the part with comparing the outputs, perhaps there's a more future-proof way of doing this?

**Comment by JonRowe** [comment]
We have a bunch of integration specs in `spec/integration` might be worth putting something together like you describe, I would also like a unit level spec that says that this count is reset after reset too though..

File: spec/integration/filtering_spec.rb [hunk 1]
```diff
@@ -66,6 +66,47 @@ def run_rerun_command_for_failing_spec
...
+          example('ex 2') { }
+        end
+      "
+
+      RSpec::Core::Formatters.register(Foo, :example_passed)
+
+      formatter = Foo.new
+      RSpec.configuration.add_formatter(formatter)
+      opts = RSpec::Core::ConfigurationOptions.new(
+        ["tmp/aruba/spec/filtering_custom_runner_spec.rb[1:1]"])
```
Comment (agis) [inline spec/integration/filtering_spec.rb:94]: @JonRowe I suspect there's a better way of doing this instead of hard-coding `tmp/aruba/` but I couldn't find it. Any ideas?

**Comment by agis** [comment]
> We have a bunch of integration specs in `spec/integration` might be worth putting something together like you describe, I would also like a unit level spec that says that this count is reset after reset too though..

Added unit and integration specs (see https://github.com/rspec/rspec-core/pull/2723#discussion_r418054921 though).

**Comment by agis** [comment]
> We have a bunch of integration specs in `spec/integration` might be worth putting something together like you describe, I would also like a unit level spec that says that this count is reset after reset too though..

> We have a bunch of integration specs in `spec/integration` might be worth putting something together like you describe, I would also like a unit level spec that says that this count is reset after reset too though..

Added unit and integration specs (see https://github.com/rspec/rspec-core/pull/2723#discussion_r418054921 though).

File: spec/integration/filtering_spec.rb [hunk 2]
```diff
@@ -66,6 +66,47 @@ def run_rerun_command_for_failing_spec
   end
 
   context "passing a line-number filter" do
+    it "works with different custom runners used in the same process" do
+      class Foo
```
Comment (JonRowe) [inline spec/integration/filtering_spec.rb:70]: I'd give this a better name, and make this an anonymous class, something like:
```suggestion
      result_counter = Class.new do
        RSpec::Core::Formatters.register(self, :example_passed)
```

File: spec/integration/filtering_spec.rb [hunk 3]
```diff
@@ -66,6 +66,47 @@ def run_rerun_command_for_failing_spec
...
+      end
+
+      write_file_formatted 'spec/filtering_custom_runner_spec.rb', "
+        RSpec.describe 'A group' do
+          example('ex 1') { }
+          example('ex 2') { }
+        end
+      "
+
+      RSpec::Core::Formatters.register(Foo, :example_passed)
```
Comment (JonRowe) [inline spec/integration/filtering_spec.rb:89]: I wondered where this was, typically we do this inside the class definition.

File: spec/integration/filtering_spec.rb [hunk 4]
```diff
@@ -66,6 +66,47 @@ def run_rerun_command_for_failing_spec
   end
 
   context "passing a line-number filter" do
+    it "works with different custom runners used in the same process" do
+      class Foo
+        attr_accessor :i
```
Comment (JonRowe) [inline spec/integration/filtering_spec.rb:71]: I know this is a dummy formatter, but I'd still name this so its clear whats happening:
```suggestion
        attr_accessor :passed_examples
```

File: spec/integration/filtering_spec.rb (hunk 1 above)
Comment (JonRowe) [reply spec/integration/filtering_spec.rb:94]: Aruba has a DSL, it includes `expand_path('file')` which returns `# => <path>/tmp/aruba/file`, that would seem like an easy win here.
https://www.rubydoc.info/gems/aruba/Aruba%2FApi%2FCore:expand_path
