### PR TITLE
Fix documentation surrounding hook order

### LINKED ISSUE #2729: Contrary to documentation,`around` hooks runs before `before`
### Subject of the issue
Contrary to documentation,`around` hooks runs before `before`

Describe your issue here.
The docs here https://www.rubydoc.info/gems/rspec-core/RSpec%2FCore%2FHooks%3Aaround says -

> All around hooks execute immediately surrounding an example, this means that all before hooks will have run and no after hooks will have run yet.

### Your environment
* Ruby version: 2.7.1p83
* rspec-core version:  3.9.2

### Steps to reproduce
Here's the example I used
```
RSpec.configure do |config|
  config.before(:each) do
    puts 'before in configure'
  end
end

RSpec.describe "Order" do
  before(:each) do
    puts 'before in describe'
  end

  around do |t|
    puts 'around started'
    t.run
    puts 'around exiting'
  end

  it 'some example' do
  end
end
```

### Expected behavior
I would expect the prints in `before` to show before the prints in `around` since 
>  all before hooks will have run 

### Actual behavior
This is the output I get
```
around started
before in configure
before in describe
around exiting
```

### PR DESCRIPTION
**Pull request by JonRowe**
Fixes #2729

### CODE REVIEW

File: lib/rspec/core/hooks.rb [hunk 1]
```diff
@@ -62,7 +62,8 @@ module Hooks
       #
       # If more than one `before` is declared within any one scope, they are run
       # in the order in which they are declared. Any `around` hooks will execute
-      # later than any `before` hook regardless of scope.
+      # after `before` context hooks but before any `before` example hook
+      # regardless of scope.
```
Comment (pirj) [inline lib/rspec/core/hooks.rb:66]: It's not quite clear what does "regardless of scope" applies to. We don't support `around(:context)` now, and in this sentence, there's a clear distinction for `before`'s scopes.

Comment (JonRowe) [reply lib/rspec/core/hooks.rb:66]: It means different context blocks, e.g. its the type of hook thats important not the block scope

Comment (pirj) [reply lib/rspec/core/hooks.rb:66]: It took me a while to understand even with your explanation. Maybe remove "regardless of scope" to avoid interpretation?

Comment (JonRowe) [reply lib/rspec/core/hooks.rb:66]: Have you got a suggested replacement?

Comment (pirj) [reply lib/rspec/core/hooks.rb:66]: So, from my point of view, the problem with those statements is that "scope" is ambiguous, it can refer to both the hook scope (`:context`/`:example`) and the context in which the hook is declared.

> hooks are stored in three scopes, which are run in order: `:suite`, `:context`, and `:example`

vs

> different context blocks

(I miserably fail at "suggested edits") WDYT of the following:
```diff
-      # If more than one `before` is declared within any one scope, they are run
-      # in the order in which they are declared. Any `around` hooks will execute
-      # after `before` context hooks but before any `before` example hook
-      # regardless of scope.
+      # If more than one `before` is declared within a context, they are run
+      # in the order in which they are declared. Any `around` hooks will execute
+      # after all `before` hooks with `:context` scope, but before any `before`
+      # hook with `:example` scope regardless of the place where any of those
+      # hooks are declared.
```

I've changed "any one" to just "a", but totally uncertain if this is worse/better.

Comment (pirj) [reply lib/rspec/core/hooks.rb:66]: > is declared within any one scope

or does this refer to `:context`/`:example` scope? Please leave this change off if so.

File: lib/rspec/core/hooks.rb [hunk 2]
```diff
@@ -265,7 +266,8 @@ def prepend_before(*args, &block)
       # This is the reverse of the order in which `before` hooks are run.
       # Similarly, if more than one `after` is declared within any one scope,
       # they are run in reverse order of that in which they are declared. Also
-      # `around` hooks will all have run before any after hooks are invoked.
+      # `around` hooks will run after any `after` example hooks are invoked but
+      # before any `after` context hooks.
```
Comment (pirj) [inline lib/rspec/core/hooks.rb:270]: Just in case you will find my previous suggestion conviencing enough, here's a similar change to this paragraph just to keep the wording more or less consistent:
```diff
      # Similarly, if more than one `after` is declared within any one scope,
      # they are run in reverse order of that in which they are declared. Also
+      # `around` hooks will run after any `after` hooks with `:example` scope
+      # are invoked but before any `after` hooks with `:context` scope.
-      # `around` hooks will run after any `after` example hooks are invoked but
-      # before any `after` context hooks.
```
