### PR TITLE
Include the pending message in json formatter output

### LINKED ISSUE #1924: JSON formatter doesn't include pending_message
The json formatter doesn't include the pending_message:

```ruby
describe 'JSON output' do
  it 'should have a pending reason' do
    pending 'so we can see the reason'
    fail
  end
end
```

```
*

Pending:
  JSON output should have a pending reason
    # so we can see the reason
    # ./my_spec.rb:4

Finished in 0 seconds (files took 0.125 seconds to load)
1 example, 0 failures, 1 pending
```

```json
{
   "examples":[
      {
         "description":"should have a pending reason",
         "full_description":"JSON output should have a pending  reason",
         "status":"pending",
         "file_path":"./my_spec.rb",
         "line_number":4,
         "run_time":0.0
      }
   ],
   "summary":{
      "duration":0.0,
      "example_count":1,
      "failure_count":0,
      "pending_count":1
   },
   "summary_line":"1 example, 0 failures, 1 pending"
}
```

the pending_message of 'so we can see the reason' shows up in the default formatter, but not the json.

### PR DESCRIPTION
**Pull request by JonRowe**
Fixes #1924

### CODE REVIEW

File: lib/rspec/core/formatters/json_formatter.rb [hunk 1]
```diff
@@ -42,6 +42,10 @@ def stop(notification)
                   :backtrace => e.backtrace,
                 }
               end
+              pm = example.execution_result.pending_message
+              if pm
+                hash[:pending_message] = pm
+              end
```
Comment (myronmarston) [inline lib/rspec/core/formatters/json_formatter.rb]: IMO, it would be better to _always_ assign a `:pending_message` key.  I (and many other experienced rubyists) have a preference for using `Hash#fetch` rather than `Hash#[]` for accessing keys in a hash created by someone else...that way, I get a clear `KeyError` if the key is renamed upstream or if I typo it.  If I use `Hash#[]` and get `nil`, I have no idea if I mispelled the key, it got renamed or just doesn't have a value.  It would be like having an object that only responds to a particular message if it has a value to return for it.

**Comment by JonRowe** [comment]
Builds failing on Travis due to support? Seems unrelated to this.

File: lib/rspec/core/formatters/json_formatter.rb (hunk 1 above)
Comment (JonRowe) [inline lib/rspec/core/formatters/json_formatter.rb]: Fair enough, it's now a blank string or the message when present

**Comment by myronmarston** [comment]
If the pending message is not set, what do you think about using `nil` for it rather than a blank string?  Seems more natural to me...after all, that's what `RSpec::Core::Example::ExecutionResult#pending_message` returns, and it seems this should mirror that.

**Comment by myronmarston** [comment]
> Builds failing on Travis due to support? Seems unrelated to this.

I pushed a commit last night to skip that spec until we fix it:

https://github.com/rspec/rspec-support/commit/9198ac30b7cfdf2915a615fdce21ee7a35a083db

**Comment by JonRowe** [comment]
I have a minor preference for an empty string (because you'd expect this to be a string value) but it's minor enough that if you'd prefer nil I'll change it.

**Comment by myronmarston** [comment]
I do prefer it.

**Comment by JonRowe** [comment]
Changed.

**Comment by myronmarston** [comment]
LGTM
